Fix Error CS0426 : The type name 'TestEnum' does not exist in the type 'Foo'. Remove double quotes. Add ExcludeFromCodeCoverage. Add tests for enum in namespace.